### ISSUE TITLE
是否考虑集成一个谷歌浏览器？

### ISSUE THREAD

**Issue by isfong** [bestwu/docker-qq#12]
比如点击QQ面板的邮箱图标，因为容器内部并没有集成浏览器所以无法打开邮箱页面了。
是否考虑加入该功能呢？
或者是否有办法设置参数将浏览器映射到主机的默认浏览器

**Comment by top-bettercode** [comment]
可以使用命令：docker exec -it qq bash 进入容器，再使用命令 apt update && apt install firefox 安装浏览器。不要安装 谷歌浏览器，无法唤起
