### ISSUE TITLE
ubuntu18.04 不出界面

### ISSUE THREAD

**Issue by Activity00** [bestwu/docker-qq#14]
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"

**Comment by top-bettercode** [comment]
日志不全，无法发现原因

**Comment by Activity00** [comment]
启动 TIM

7-Zip [32] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=zh_CN.UTF-8,Utf16=on,HugeFiles=on,32 bits,4 CPUs AMD A10-7300 Radeon R6, 10 Compute Cores 4C+6G  (630F01),ASM,AES-NI)

Scanning the drive for archives:
1 file, 87597038 bytes (84 MiB)

Extracting archive: /opt/deepinwine/apps/Deepin-TIM/files.7z
--
Path = /opt/deepinwine/apps/Deepin-TIM/files.7z
Type = 7z
Physical Size = 87597038
Headers Size = 16349
Method = LZMA2:26 BCJ2
Solid = +
Blocks = 1

Everything is Ok

Folders: 272
Files: 1483
Size:       289707192
Compressed: 87597038
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine version: 2.18
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/home/qq/.deepinwine/Deepin-TIM' has been updated.

**Comment by top-bettercode** [comment]
有其他错误提示吗，目前的日志看起来没什么问题，是到最后一行就退出了吗？

**Comment by Activity00** [comment]
是的最后一行后就没反应了，没有界面出来。已经xhost +

**Comment by top-bettercode** [comment]
docker 容器退出了，还是在运行？

**Comment by Activity00** [comment]
在运行

**Comment by top-bettercode** [comment]
ubuntu桌面是gnome还是kde?

**Comment by Activity00** [comment]
gnome

**Comment by top-bettercode** [comment]
未发现错误信息和原因，可以试试下载最新的镜像（docker pull bestwu/qq:office）,新镜像调整了下启动脚本
