### ISSUE TITLE
每天自动关闭进程

### ISSUE THREAD

**Issue by joe104** [bestwu/docker-qq#15]
这几天都是8点多开启，下午17点多自动关闭，每天自动关闭进程，是否哪里可以设置？
> 

~# docker ps -l
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                    PORTS               NAMES
ced5707c66cd        bestwu/qq:office    "/entrypoint.sh"    11 days ago         Exited (0) 15 hours ago                       qq

>

**Comment by top-bettercode** [comment]
自动关闭是由于运行出错，进程被杀死了。这个问题确实存在，目前未找到解决办法。待后续观察

**Comment by top-bettercode** [comment]
最新镜像调整了启动脚本，目前本机测试，没再出现自动关闭进程的问题，可以下载试下，
