### ISSUE TITLE
不能发送中文

### ISSUE THREAD

**Issue by zbge** [bestwu/docker-qq#17]
ubuntu18.04安装了tim后，能正常访问，但是无法获取系统自带的中文输入法，输入中文，这个请问怎么解决，docker新手

**Comment by top-bettercode** [comment]
```
 - XMODIFIERS=@im=fcitx #中文输入
 - QT_IM_MODULE=fcitx
 - GTK_IM_MODULE=fcitx
```
这几项是配置输入法的，如果系统是ibus类的输入法，将fcitx换为ibus

**Comment by zbge** [comment]
谢谢，忘了看自己系统是什么类输入法了，已修改。但发现一个新问题，改成 ibus 后不能输入密码，可以使用小键盘输入，扫二维码登录
