### ISSUE TITLE
提示版本存在安全风险

### ISSUE THREAD

**Issue by kenneth104** [bestwu/docker-qq#21]
安装好之后正常使用，然后忽然无法输入中文，随后关掉容器再开，提示当前版本存在安全风险

system：deepin 15.11 (base on debian 9.0)
core：4.15.0-29deepin-generic
docker：19.03.4
image: bestwu/qq:im

![深度截图_选择区域_20191107125637.png](https://ww1.sinaimg.cn/large/698fb600gy1g8peaj37xtj20bu01umx6.jpg)

**Comment by kenneth104** [comment]
多次尝试的结果
1，qq:im，原版，提示“当前版本存在安全风险”，腾讯封杀了老版本协议
2，qq:latest，轻聊版，扫码登录闪退，后续没测试
3，qq:office，TIM，暂时正常

**Comment by kenneth104** [comment]
挂通宵，又断了
现在尝试TIM版本

**Comment by top-bettercode** [comment]
Duplicate of #27
