### ISSUE TITLE
字体发虚

### ISSUE THREAD

**Issue by kenneth104** [bestwu/docker-qq#22]
system：deepin 15.11 (base on debian 9.0)
core：4.15.0-29deepin-generic
docker：19.03.4
image: bestwu/qq:im

![深度截图_选择区域_20191107133703.png](https://ws1.sinaimg.cn/large/698fb600gy1g8pf4nkguuj20l60f9jt2.jpg)

**Comment by top-bettercode** [comment]
可以试下安装 文泉驿微米黑 字体

**Comment by kenneth104** [comment]
开发你好，系统已经有该字体，是需要安装到docker的wine里面么？
将该字体设置为系统默认，也是一样的发虚

**Comment by top-bettercode** [comment]
你的是HiDPI显示器吗

**Comment by kenneth104** [comment]
显示器是27寸，2560*1440

**Comment by top-bettercode** [comment]
Duplicate of #30
