### ISSUE TITLE
No protocal specified

### ISSUE THREAD

**Issue by COOLMSF** [bestwu/docker-qq#24]
昨天都还能正常启动， 现在报错：

total 0
lrwxrwxrwx 1 qq qq 10 2月  17 13:41 c: -> ../drive_c
lrwxrwxrwx 1 qq qq 10 2月  17 13:41 com1 -> /dev/ttyS0
lrwxrwxrwx 1 qq qq 10 2月  17 13:41 com2 -> /dev/ttyS1
lrwxrwxrwx 1 qq qq 10 2月  17 13:41 com3 -> /dev/ttyS2
lrwxrwxrwx 1 qq qq 10 2月  17 13:41 com4 -> /dev/ttyS3
lrwxrwxrwx 1 qq qq  8 2月  17 13:41 lpt1 -> /dev/lp0
lrwxrwxrwx 1 qq qq  1 2月  17 13:41 z: -> /
2020年 02月 17日 星期一 13:41:17 UTC:CallApp Deepin-TIM  
2020年 02月 17日 星期一 13:41:17 UTC:kill TIM.exe block
2020年 02月 17日 星期一 13:41:17 UTC:No wine process found
2020年 02月 17日 星期一 13:41:17 UTC:start running...
No protocol specified
No protocol specified
No protocol specified
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"

**Comment by top-bettercode** [comment]
这个链接也许对你有帮助：https://unix.stackexchange.com/questions/85782/error-no-protocol-specified-when-running-from-remote-machine-via-ssh

**Comment by COOLMSF** [comment]
> 这个链接也许对你有帮助：https://unix.stackexchange.com/questions/85782/error-no-protocol-specified-when-running-from-remote-machine-via-ssh

解决了， 谢谢
