### ISSUE TITLE
上不了网

### ISSUE THREAD

**Issue by COOLMSF** [bestwu/docker-qq#25]
系统：manjaro i3 5.4.18-1-MANJARO
之前装好没问题， 突然连不上网络了。

运行 docker logs qq 结果如下
`realpath: missing operand
Try 'realpath --help' for more information.
2020年 02月 17日 星期一 18:37:03 UTC:Run Deepin-TIM 2.0.0deepin4
2020年 02月 17日 星期一 18:37:03 UTC:run Deepin-TIM progress pid 

7-Zip [32] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=zh_CN.UTF-8,Utf16=on,HugeFiles=on,32 bits,8 CPUs Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (806EA),ASM,AES-NI)

Scanning the drive for archives:
1 file, 87597038 bytes (84 MiB)

Extracting archive: /opt/deepinwine/apps/Deepin-TIM/files.7z
--
Path = /opt/deepinwine/apps/Deepin-TIM/files.7z
Type = 7z
Physical Size = 87597038
Headers Size = 16349
Method = LZMA2:26 BCJ2
Solid = +
Blocks = 1

Everything is Ok

Folders: 272
Files: 1483
Size:       289707192
Compressed: 87597038
total 0
lrwxrwxrwx 1 qq qq 10 2月  17 18:37 c: -> ../drive_c
lrwxrwxrwx 1 qq qq 10 2月  17 18:37 com1 -> /dev/ttyS0
lrwxrwxrwx 1 qq qq 10 2月  17 18:37 com2 -> /dev/ttyS1
lrwxrwxrwx 1 qq qq 10 2月  17 18:37 com3 -> /dev/ttyS2
lrwxrwxrwx 1 qq qq 10 2月  17 18:37 com4 -> /dev/ttyS3
lrwxrwxrwx 1 qq qq  8 2月  17 18:37 lpt1 -> /dev/lp0
lrwxrwxrwx 1 qq qq  1 2月  17 18:37 z: -> /
2020年 02月 17日 星期一 18:37:09 UTC:CallApp Deepin-TIM  
2020年 02月 17日 星期一 18:37:09 UTC:kill TIM.exe block
2020年 02月 17日 星期一 18:37:09 UTC:No wine process found
2020年 02月 17日 星期一 18:37:09 UTC:start running...
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine version: 2.18
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/home/qq/.deepinwine/Deepin-TIM' has been updated.
wine: cannot find L"c:\\Program Files\\Tencent\\TIM\\Bin\\TXPlatform.exe"
`

**Comment by top-bettercode** [comment]
Duplicate of #23
