### ISSUE TITLE
执行docker-compose up -d  time out

### ISSUE THREAD

**Issue by Luo-Zhongwei** [bestwu/docker-qq#26]
lzw@resplendent-star:~$ docker-compose up -d
WARNING: The GID variable is not set. Defaulting to a blank string.
WARNING: The UID variable is not set. Defaulting to a blank string.
Pulling qq (bestwu/qq:office)...
ERROR: Get https://registry-1.docker.io/v2/bestwu/qq/manifests/office: Get https://auth.docker.io/token?scope=repository%3Abestwu%2Fqq%3Apull&service=registry.docker.io: net/http: TLS handshake timeout

**Comment by rammiah** [comment]
docker下载超时，去网上找一下如何给docker挂代理或者替换成国内的源。可以参考一下这个[Docker中国源](https://www.jianshu.com/p/405fe33b9032)

**Comment by Luo-Zhongwei** [comment]
> docker下载过期，去网上找一下如何给docker挂代理或替换成国内的源。可以参考一下这个[Docker中国源](https://www.jianshu.com/p/405fe33b9032)

谢谢
