### ISSUE TITLE
Ubuntu16.04 登录 提示 qq版本低,要求下载

### ISSUE THREAD

**Issue by sengeiou** [bestwu/docker-qq#27]
是否能更新个新版本,非常感谢,原来的版本很好用,起码比官方Linux版本好用,感谢!!!!!!

**Comment by top-bettercode** [comment]
解压运行 run.sh，可根据本机具体情况修改脚本

[update.zip](https://github.com/bestwu/docker-qq/files/4354797/update.zip)

**Comment by sengeiou** [comment]
> 解压运行 run.sh，可根据本机具体情况修改脚本
> 
> [update.zip](https://github.com/bestwu/docker-qq/files/4354797/update.zip)

感谢大佬,可以用了,感谢让我摆脱简陋的Linux 版本的QQ 感谢
