### ISSUE TITLE
如何用 docker qq 传文件呢,打开传文件的地方,找不到本机的文件系统

### ISSUE THREAD

**Issue by Luo-Zhongwei** [bestwu/docker-qq#28]
![2020-05-02 15-52-23屏幕截图](https://user-images.githubusercontent.com/41502003/80858634-1f33fe80-8c8d-11ea-8b1e-342ba3ebff2d.png)

**Comment by WalkerGH** [comment]
脚本中的 -v $HOME/WeChatFiles:/WeChatFiles \    Ubuntu20.04   $HOME 改成自己的绝对路径就可以了 eg：/home/bestwu
