### ISSUE TITLE
Fedora27 运行失败

### ISSUE THREAD

**Issue by mzz2017** [bestwu/docker-qq#3]
```powershell
[mzz@mzz-pub ~]$ docker logs qq
chown: 正在更改'/TencentFiles' 的所有者: 权限不够
启动 TIM
7-Zip [32] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=zh_CN.UTF-8,Utf16=on,HugeFiles=on,32 bits,8 CPUs Intel(R) Xeon(R) CPU E3-1230 V2 @ 3.30GHz (306A9),ASM,AES-NI)
Scanning the drive for archives:
1 file, 73454263 bytes (71 MiB)
Extracting archive: /opt/deepinwine/apps/Deepin-TIM/files.7z
--
Path = /opt/deepinwine/apps/Deepin-TIM/files.7z
Type = 7z
Physical Size = 73454263
Headers Size = 15402
Method = LZMA2:26 BCJ2
Solid = +
Blocks = 1
Everything is Ok
Folders: 269
Files: 1314
Size:       253220795
Compressed: 73454263
/usr/bin/env: "python2": 没有那个文件或目录
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/home/qq/.deepinwine/Deepin-TIM' has been updated.
```
试过更改`/etc/ssh/ssh_config`了，追加了
```Ruby
   ForwardX11 yes
   ForwardX11Trusted yes
```
还是不行。

**Comment by top-bettercode** [comment]
请尝试检查并修改挂载的/TencentFiles文件夹权限

在 2018年1月30日，19:16，mzz <notifications@github.com<mailto:notifications@github.com>> 写道：


[mzz@mzz-pub ~]$ docker logs qq
chown: 正在更改'/TencentFiles' 的所有者: 权限不够
启动 TIM
7-Zip [32] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=zh_CN.UTF-8,Utf16=on,HugeFiles=on,32 bits,8 CPUs Intel(R) Xeon(R) CPU E3-1230 V2 @ 3.30GHz (306A9),ASM,AES-NI)
Scanning the drive for archives:
1 file, 73454263 bytes (71 MiB)
Extracting archive: /opt/deepinwine/apps/Deepin-TIM/files.7z
--
Path = /opt/deepinwine/apps/Deepin-TIM/files.7z
Type = 7z
Physical Size = 73454263
Headers Size = 15402
Method = LZMA2:26 BCJ2
Solid = +
Blocks = 1
Everything is Ok
Folders: 269
Files: 1314
Size:       253220795
Compressed: 73454263
/usr/bin/env: "python2": 没有那个文件或目录
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/home/qq/.deepinwine/Deepin-TIM' has been updated.

试过更改/etc/ssh/ssh_config了，追加了

   ForwardX11 yes
   ForwardX11Trusted yes

还是不行。

**Comment by mzz2017** [comment]
感谢！！问题得到解决！！
运行容器时加上参数`--privileged=true`即可

**Comment by mzz2017** [comment]
在Fedora可以记住密码和自动登录，也会有新消息提示。
但新问题是：
1，使用截图功能会截到"花屏"，多试几遍就会崩溃。
![tim 20180130220517](https://user-images.githubusercontent.com/30586220/35570306-cc028206-0609-11e8-925d-e2efc021eef1.png)

2，没有任务栏图标，会出现一个叫做“Wine System Tray”的浮动窗口，做着跟任务栏一样的工作。
![t2](https://user-images.githubusercontent.com/30586220/35570469-436b5e4e-060a-11e8-9a4b-80f869511886.jpg)

**Comment by top-bettercode** [comment]
1.Wayland 显示服务器，截图功能不能正常使用，可尝试/etc/gdm/custom.conf文件中解除WaylandEnable=false的注释重启电脑。
2.gnome 托盘可安装 gnome  [TopIcons Plus](https://extensions.gnome.org/extension/1031/topicons/)插件固定托盘到顶栏

**Comment by mzz2017** [comment]
问题得到完美解决！谢谢！
