### ISSUE TITLE
执行 sh后，无法展示出页面

### ISSUE THREAD

**Issue by ghost** [bestwu/docker-qq#34]
打印日志是这样的
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x0
  Serial number of failed request:  10
  Current serial number in output stream:  10

-- 系统 Arch Linux + kde 桌面

**Comment by top-bettercode** [comment]
install gnome-settings-daemon，run /usr/lib/gsd-xsettings
or
install xfce4-settings, run /usr/bin/xfsettingsd

see https://www.cnblogs.com/fly2wind/p/10680428.html
