### ISSUE TITLE
无法安装  sudo apt-get install -y deepin.com.qq.office

### ISSUE THREAD

**Issue by Luo-Zhongwei** [bestwu/docker-qq#38]
sudo apt-get install -y deepin.com.qq.office
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
E: 无法定位软件包 deepin.com.qq.office
E: 无法按照 glob ‘deepin.com.qq.office’ 找到任何软件包
E: 无法按照正则表达式 deepin.com.qq.office 找到任何软件包

**Comment by WindSpiritSR** [comment]
删除旧镜像重新拉取
