### ISSUE TITLE
qq和tim窗口经常消失

### ISSUE THREAD

**Issue by huxuhui228** [bestwu/docker-qq#40]
系统是xububtu 20.04，安装启动正常，但登录后经常窗口消失，尤其是发送文件、拖动窗口、放大缩小窗口时。
日志如下：
tim    | X Error of failed request:  BadValue (integer parameter out of range for operation)
tim    |   Major opcode of failed request:  130 (MIT-SHM)
tim    |   Minor opcode of failed request:  3 (X_ShmPutImage)
tim    |   Value in failed request:  0x240
tim    |   Serial number of failed request:  151440
tim    |   Current serial number in output stream:  151440
tim    | 退出

$ sudo docker-compose ps -a
Name      Command        State     Ports
----------------------------------------
qq     /entrypoint.sh   Exit 137        
tim    /entrypoint.sh   Exit 0

**Comment by top-bettercode** [comment]
可尝试禁用 “MIT-SHM”共享X进程内存的功能

具体操作：

vi /etc/X11/xorg.conf

增加：

 Section "Extensions"
     Option "MIT-SHM" "Disable"
 EndSection

重启系统

**Comment by huxuhui228** [comment]
谢谢回复，果然管用，用了几天一直没关机也不消失了。只是vnc连不上了，今天才找到原因，得在x11vnc启动的时候加上-noshm参数就行了。
祝您新年快乐。
















在 2021-02-05 16:58:28，"Peter Wu" <notifications@github.com> 写道：

可尝试禁用 “MIT-SHM”共享X进程内存的功能

具体操作：

vi /etc/X11/xorg.conf

增加：

Section "Extensions"
Option "MIT-SHM" "Disable"
EndSection

重启系统
