### ISSUE TITLE
在Centos7.5下能用吗？运行时弹出错误窗口“initialization failure:0X00000030”

### ISSUE THREAD

**Issue by chaowei1982** [bestwu/docker-qq#41]
在Centos7.5下运行时弹出错误窗口“initialization failure:0X00000030”

运行#docker logs TIM显示如下错误：
启动 TIM
2021年 02月 23日 星期二 16:41:37 UTC:Run Deepin-TIM 2.0.0deepin4
2021年 02月 23日 星期二 16:41:37 UTC:run Deepin-TIM progress pid 

** (zenity:46): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-eYTkxMFJ4g: 拒绝连接
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
total 0
lrwxrwxrwx 1 root root 10 2月  23 16:42 c: -> ../drive_c
lrwxrwxrwx 1 root root 10 2月  23 16:41 com1 -> /dev/ttyS0
lrwxrwxrwx 1 root root 10 2月  23 16:41 com2 -> /dev/ttyS1
lrwxrwxrwx 1 root root 10 2月  23 16:41 com3 -> /dev/ttyS2
lrwxrwxrwx 1 root root 10 2月  23 16:41 com4 -> /dev/ttyS3
lrwxrwxrwx 1 root root  8 2月  23 16:41 lpt1 -> /dev/lp0
lrwxrwxrwx 1 root root  1 2月  23 16:42 z: -> /
2021年 02月 23日 星期二 16:42:59 UTC:CallApp Deepin-TIM  
2021年 02月 23日 星期二 16:42:59 UTC:kill TIM.exe block
2021年 02月 23日 星期二 16:42:59 UTC:No wine process found
2021年 02月 23日 星期二 16:42:59 UTC:start running...
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine version: 2.18
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/home/qq/.deepinwine/Deepin-TIM' has been updated.
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  130 (MIT-SHM)
  Minor opcode of failed request:  3 (X_ShmPutImage)
  Value in failed request:  0x1ef
  Serial number of failed request:  542
  Current serial number in output stream:  543

**Comment by top-bettercode** [comment]
可尝试禁用 “MIT-SHM”共享X进程内存的功能

具体操作：

vi /etc/X11/xorg.conf

增加：

Section "Extensions"
Option "MIT-SHM" "Disable"
EndSection

重启系统

**Comment by chaowei1982** [comment]
禁用 “MIT-SHM”后解决了弹窗问题，可以在Centos 7.5下正常使用！
感谢作者提供这么好用的docker QQ！
