### ISSUE TITLE
centos 上无法运行

### ISSUE THREAD

**Issue by woodwei** [bestwu/docker-qq#43]
我的系统是centos 7，如果运行bestwu/qq:office这个映像，可以出界面但是提示版本旧需要升级，如果运行bestwu/qq这个映像（qqlight？），则不出界面，错误信息为：

启动 QQLight

7-Zip [32] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=zh_CN.UTF-8,Utf16=on,HugeFiles=on,32 bits,8 CPUs Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (906EA),ASM,AES-NI)

Scanning the drive for archives:
1 file, 57028555 bytes (55 MiB)

Extracting archive: /opt/deepinwine/apps/Deepin-QQLight/files.7z
--
Path = /opt/deepinwine/apps/Deepin-QQLight/files.7z
Type = 7z
Physical Size = 57028555
Headers Size = 13846
Method = LZMA2:26 BCJ2
Solid = +
Blocks = 1

Everything is Ok

Folders: 197
Files: 1236
Size:       200038625
Compressed: 57028555
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine version: 2.18
wine: Unhandled page fault on read access to 0xc60b770e at address 0x7e814050 (thread 0019), starting debugger...
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/home/qq/.deepinwine/Deepin-QQLight' has been updated.

我的桌面是KDE，不是GNOME，不知道是否和这个有关（但是TIM能出界面，又不像）。
希望帮忙解决，非常感谢！

**Comment by woodwei** [comment]
后来发现，尽管第一次用
run -d --name qq \
--device /dev/snd --ipc=host \
-v $HOME/TencentFiles:/TencentFiles \
-v /tmp/.X11-unix:/tmp/.X11-unix \
-e XMODIFIERS=@im=ibus \
-e QT_IM_MODULE=ibus \
-e GTK_IM_MODULE=ibus \
-e DISPLAY=unix$DISPLAY \
-e AUDIO_GID=`getent group audio | cut -d: -f3` \
-e VIDEO_GID=`getent group video | cut -d: -f3` \
-e GID=`id -g` \
-e UID=`id -u` \
bestwu/qq:latest
不出界面，但是后续如果docker start qq就可以出登录界面了。应该是能用了。谢谢你的工作！

**Comment by top-bettercode** [comment]
因是基于wine运行，所以可能有这种不稳定的情况出现，包括可能的闪退等
